[package]
name = "alight-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alight-types.workspace = true
alight-canary.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
alight-model.workspace = true
serde_json.workspace = true

[lints]
workspace = true
